server:
  port: 8081
  servlet:
    context-path: /walle
spring:
  data:
    mongodb:
      host: 8.136.128.218
      port: 27017
      database: lcx
      username: root
      password: MG123lcx
      authentication-database: admin
#      uuid-representation: java_legacy
#      repositories:
#        type: auto
